import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/theme/app_palette.dart';
import '../../../profile/application/profile_settings_provider.dart';
import '../models/salah_trainer_models.dart';
import 'prayer_posture_animator.dart';

/// The scene drawn for a posture: a robed silhouette on a prayer mat facing
/// the mihrab, generated by tooling/art_src/salah_art/generate_salah_art.mjs.
String salahPostureArtAsset(PrayerPostureType posture) {
  final name = switch (posture) {
    PrayerPostureType.takbir => 'takbir',
    PrayerPostureType.qiyam => 'qiyam',
    PrayerPostureType.ruku => 'ruku',
    PrayerPostureType.qawmah => 'qawmah',
    PrayerPostureType.sujud => 'sujud',
    PrayerPostureType.jalsah => 'jalsah',
    PrayerPostureType.tashahhud => 'tashahhud',
    PrayerPostureType.salamRight => 'salam_right',
    PrayerPostureType.salamLeft => 'salam_left',
  };
  return 'assets/images/salah_art/posture_$name.webp';
}

/// The guided step's hero: the posture scene in a 16:9 frame that crossfades
/// when the posture changes. A scene that fails to load falls back to the
/// vector figure, so the card never goes blank.
class SalahPostureArt extends ConsumerWidget {
  const SalahPostureArt({super.key, required this.posture});

  final PrayerPostureType posture;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final reduceMotion = ref.watch(
      profileSettingsProvider.select((value) => value.reduceMotion),
    );
    final accent = context.palette.accent;
    return ClipRRect(
      borderRadius: BorderRadius.circular(18),
      child: Container(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18),
          border: Border.all(color: accent.withValues(alpha: 0.18)),
        ),
        child: AspectRatio(
          aspectRatio: 16 / 9,
          child: AnimatedSwitcher(
            duration: Duration(milliseconds: reduceMotion ? 0 : 320),
            switchInCurve: Curves.easeOut,
            switchOutCurve: Curves.easeIn,
            child: Image.asset(
              salahPostureArtAsset(posture),
              key: ValueKey(posture),
              fit: BoxFit.cover,
              gaplessPlayback: true,
              errorBuilder: (context, error, stackTrace) => Center(
                child: PrayerPostureAnimator(posture: posture, size: 140),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
