// GENERATED by tooling/art_src/garden_art/generate_garden_art.mjs — do not edit.
// Regenerate with: node tooling/art_src/garden_art/generate_garden_art.mjs
//
// The vista's design space is 2000x1200; every coordinate below
// lives in that space. Positions exist ONLY in the generator's LAYOUT — the
// app must read them from here and never hardcode a coordinate in a widget.

class GardenLayerRect {
  const GardenLayerRect(this.x, this.y, this.w, this.h);

  final double x;
  final double y;
  final double w;
  final double h;
}

class GardenLayerPlacement {
  const GardenLayerPlacement({
    required this.z,
    required this.rect,
    required this.baseX,
    required this.baseY,
  });

  final int z;
  final GardenLayerRect rect;
  final double baseX;
  final double baseY;
}

abstract final class GardenSceneLayout {
  static const double canvasWidth = 2000;
  static const double canvasHeight = 1200;
  static const double horizonY = 600;

  static const GardenLayerRect heroCrop = GardenLayerRect(130, 0, 1740, 1200);
  static const GardenLayerRect homeCardCrop = GardenLayerRect(
    100,
    280,
    1800,
    800,
  );
  static const GardenLayerRect groundRect = GardenLayerRect(0, 540, 2000, 660);
  static const GardenLayerRect waterRect = GardenLayerRect(1040, 560, 960, 640);
  static const GardenLayerRect beehiveRect = GardenLayerRect(826, 614, 92, 100);

  static const Map<String, GardenLayerPlacement> elementPlacements = {
    'loteTree': GardenLayerPlacement(
      z: 30,
      rect: GardenLayerRect(1700, 520, 260, 270),
      baseX: 1830,
      baseY: 770,
    ),
    'datePalm': GardenLayerPlacement(
      z: 32,
      rect: GardenLayerRect(90, 640, 440, 420),
      baseX: 300,
      baseY: 1040,
    ),
    'olive': GardenLayerPlacement(
      z: 34,
      rect: GardenLayerRect(380, 800, 300, 220),
      baseX: 520,
      baseY: 1010,
    ),
    'fig': GardenLayerPlacement(
      z: 36,
      rect: GardenLayerRect(600, 830, 270, 200),
      baseX: 735,
      baseY: 1020,
    ),
    'centralTree': GardenLayerPlacement(
      z: 40,
      rect: GardenLayerRect(620, 300, 760, 700),
      baseX: 1000,
      baseY: 990,
    ),
    'pomegranate': GardenLayerPlacement(
      z: 44,
      rect: GardenLayerRect(1440, 860, 250, 190),
      baseX: 1565,
      baseY: 1040,
    ),
    'grapeVine': GardenLayerPlacement(
      z: 46,
      rect: GardenLayerRect(1640, 830, 300, 195),
      baseX: 1785,
      baseY: 1015,
    ),
    'gourd': GardenLayerPlacement(
      z: 48,
      rect: GardenLayerRect(1090, 1060, 220, 90),
      baseX: 1195,
      baseY: 1132,
    ),
    'rayhan': GardenLayerPlacement(
      z: 50,
      rect: GardenLayerRect(750, 1030, 220, 110),
      baseX: 855,
      baseY: 1124,
    ),
    'hoopoe': GardenLayerPlacement(
      z: 52,
      rect: GardenLayerRect(1080, 990, 150, 120),
      baseX: 1150,
      baseY: 1052,
    ),
    'ant': GardenLayerPlacement(
      z: 54,
      rect: GardenLayerRect(900, 1120, 140, 40),
      baseX: 970,
      baseY: 1140,
    ),
  };

  static const List<List<double>> streamCenterline = [
    [1490, 620],
    [1462, 750],
    [1396, 820],
    [1430, 890],
    [1352, 960],
    [1392, 1030],
    [1308, 1105],
    [1330, 1205],
  ];
  static const GardenLayerRect fireflyRegion = GardenLayerRect(
    600,
    700,
    700,
    220,
  );
  static const List<List<double>> beeAnchors = [
    [700, 905],
    [940, 846],
    [610, 834],
  ];
  static const List<double> fishAnchor = [1360, 1058];
  static const List<double> beehiveAnchor = [872, 664];
  static const double birdBandTop = 200;
  static const double birdBandBottom = 360;

  /// WebP layers that exist under assets/images/garden_art/. The asset
  /// resolver walks variants/stages downward through this set and falls back
  /// to the placeholder painter when nothing is available.
  static const Set<String> availableGardenArtFiles = <String>{
    'garden_animal_ants.webp',
    'garden_animal_beehive.webp',
    'garden_animal_hoopoe.webp',
    'garden_ground_day.webp',
    'garden_ground_night.webp',
    'garden_milestone_m01.webp',
    'garden_milestone_m02.webp',
    'garden_milestone_m03.webp',
    'garden_milestone_m04.webp',
    'garden_milestone_m05.webp',
    'garden_milestone_m06.webp',
    'garden_milestone_m07.webp',
    'garden_milestone_m08.webp',
    'garden_milestone_m09.webp',
    'garden_milestone_m10.webp',
    'garden_plant_fig_v1.webp',
    'garden_plant_fig_v2.webp',
    'garden_plant_fig_v3.webp',
    'garden_plant_gourd_v1.webp',
    'garden_plant_gourd_v2.webp',
    'garden_plant_gourd_v3.webp',
    'garden_plant_olive_v1.webp',
    'garden_plant_olive_v2.webp',
    'garden_plant_olive_v3.webp',
    'garden_plant_palm_v1.webp',
    'garden_plant_palm_v2.webp',
    'garden_plant_palm_v3.webp',
    'garden_plant_pomegranate_v1.webp',
    'garden_plant_pomegranate_v2.webp',
    'garden_plant_pomegranate_v3.webp',
    'garden_plant_rayhan_v1.webp',
    'garden_plant_rayhan_v2.webp',
    'garden_plant_rayhan_v3.webp',
    'garden_plant_sidr_v1.webp',
    'garden_plant_sidr_v2.webp',
    'garden_plant_vine_v1.webp',
    'garden_plant_vine_v2.webp',
    'garden_plant_vine_v3.webp',
    'garden_sky_dawn_day.webp',
    'garden_sky_dawn_night.webp',
    'garden_sky_evening_day.webp',
    'garden_sky_evening_night.webp',
    'garden_sky_morning_day.webp',
    'garden_sky_morning_night.webp',
    'garden_sky_warm_day.webp',
    'garden_sky_warm_night.webp',
    'garden_tree_s01.webp',
    'garden_tree_s02.webp',
    'garden_tree_s03.webp',
    'garden_tree_s04.webp',
    'garden_tree_s05_canopy.webp',
    'garden_tree_s05_trunk.webp',
    'garden_tree_s06_canopy.webp',
    'garden_tree_s06_trunk.webp',
    'garden_tree_s07_canopy.webp',
    'garden_tree_s07_trunk.webp',
    'garden_tree_s08_canopy.webp',
    'garden_tree_s08_trunk.webp',
    'garden_tree_s09_canopy.webp',
    'garden_tree_s09_trunk.webp',
    'garden_tree_s10_canopy.webp',
    'garden_tree_s10_trunk.webp',
    'garden_water_e01.webp',
    'garden_water_e01_night.webp',
    'garden_water_e02.webp',
    'garden_water_e02_night.webp',
    'garden_water_e03.webp',
    'garden_water_e03_night.webp',
    'garden_water_e04.webp',
    'garden_water_e04_night.webp',
    'garden_water_e05.webp',
    'garden_water_e05_night.webp',
  };
}
