// Path of Nur — Living Garden Vista art generator.
// P3 (layout skeleton): the LAYOUT object below is the single source of truth
// for every element's position in the 2000x1200 design space. Running this
// script emits lib/features/garden/data/garden_scene_layout.g.dart so code and
// art can never disagree about coordinates. Art waves (P4/P5) add SVG painters
// here that render WebP layers into assets/images/garden_art/ and list them in
// AVAILABLE_FILES; the app's resolver downgrades gracefully until then.
//
// Style contract (matches learn_art + the approved painterly preview):
// volumetric calm — soft gradient skies, warm ivory light, gold accents,
// no faces, no figures, no text baked into artwork.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..', '..');
const DART_OUT = join(REPO, 'lib', 'features', 'garden', 'data', 'garden_scene_layout.g.dart');

const CANVAS = { w: 2000, h: 1200, horizonY: 600 };

// Crop windows. Hero matches the existing 1.45:1 GardenPage frame; the Home
// card is a low wide band that keeps the tree base and stream mouth visible.
const CROPS = {
  hero: { x: 130, y: 0, w: 1740, h: 1200 },
  homeCard: { x: 100, y: 280, w: 1800, h: 800 },
};

// Element placements: tight art rects in design space, z order back-to-front,
// and the ground anchor each element stands on (also the sway pivot's x).
// Ids must match GardenSceneElementId names in garden_scene_models.dart.
const ELEMENTS = {
  loteTree:    { z: 30, rect: [1700, 520, 260, 270], base: [1830, 770] },
  datePalm:    { z: 32, rect: [90, 640, 440, 420],   base: [300, 1040] },
  olive:       { z: 34, rect: [380, 800, 300, 220],  base: [520, 1010] },
  fig:         { z: 36, rect: [600, 830, 270, 200],  base: [735, 1020] },
  centralTree: { z: 40, rect: [620, 300, 760, 700],  base: [1000, 990] },
  pomegranate: { z: 44, rect: [1440, 860, 250, 190], base: [1565, 1040] },
  grapeVine:   { z: 46, rect: [1640, 830, 300, 195], base: [1785, 1015] },
  gourd:       { z: 48, rect: [1090, 1060, 220, 90], base: [1195, 1132] },
  rayhan:      { z: 50, rect: [750, 1030, 220, 110], base: [855, 1124] },
  hoopoe:      { z: 52, rect: [1080, 990, 150, 120], base: [1150, 1052] },
  ant:         { z: 54, rect: [900, 1120, 140, 40],  base: [970, 1140] },
};

// Full-region raster layer rects (files are cropped to these regions).
const REGIONS = {
  ground: [0, 540, 2000, 660],
  water: [1140, 560, 560, 640],
};

// Painter-only motion anchors (no raster files): the motion layer draws bees,
// birds, fish ripples, fireflies and water shimmer at these positions.
const MOTION = {
  streamCenterline: [
    [1490, 620], [1462, 750], [1396, 820], [1430, 890],
    [1352, 960], [1392, 1030], [1308, 1105], [1330, 1205],
  ],
  fireflyRegion: [600, 700, 700, 220],
  beeAnchors: [[700, 905], [940, 846], [610, 834]],
  fishAnchor: [1360, 1058],
  beehiveAnchor: [872, 664],
  birdBand: [200, 360],
};

// WebP files that actually exist in assets/images/garden_art/. Art waves
// append here as layers are produced; the resolver treats absence as
// "placeholder painter covers it", never a broken image.
const AVAILABLE_FILES = [];

function rectConst(r) {
  return `GardenLayerRect(${r[0]}, ${r[1]}, ${r[2]}, ${r[3]})`;
}

function emitDart() {
  const placements = Object.entries(ELEMENTS)
    .map(([id, e]) =>
      `    '${id}': GardenLayerPlacement(\n` +
      `      z: ${e.z},\n` +
      `      rect: ${rectConst(e.rect)},\n` +
      `      baseX: ${e.base[0]},\n` +
      `      baseY: ${e.base[1]},\n` +
      `    ),`)
    .join('\n');
  const centerline = MOTION.streamCenterline.map((p) => `[${p[0]}, ${p[1]}]`).join(', ');
  const bees = MOTION.beeAnchors.map((p) => `[${p[0]}, ${p[1]}]`).join(', ');
  const files = AVAILABLE_FILES.map((f) => `    '${f}',`).join('\n');
  const dart = `// GENERATED by tooling/art_src/garden_art/generate_garden_art.mjs — do not edit.
// Regenerate with: node tooling/art_src/garden_art/generate_garden_art.mjs
//
// The vista's design space is ${CANVAS.w}x${CANVAS.h}; every coordinate below
// lives in that space. Positions exist ONLY in the generator's LAYOUT — the
// app must read them from here and never hardcode a coordinate in a widget.

class GardenLayerRect {
  const GardenLayerRect(this.x, this.y, this.w, this.h);

  final double x;
  final double y;
  final double w;
  final double h;
}

class GardenLayerPlacement {
  const GardenLayerPlacement({
    required this.z,
    required this.rect,
    required this.baseX,
    required this.baseY,
  });

  final int z;
  final GardenLayerRect rect;
  final double baseX;
  final double baseY;
}

abstract final class GardenSceneLayout {
  static const double canvasWidth = ${CANVAS.w};
  static const double canvasHeight = ${CANVAS.h};
  static const double horizonY = ${CANVAS.horizonY};

  static const GardenLayerRect heroCrop = ${rectConst([CROPS.hero.x, CROPS.hero.y, CROPS.hero.w, CROPS.hero.h])};
  static const GardenLayerRect homeCardCrop = ${rectConst([CROPS.homeCard.x, CROPS.homeCard.y, CROPS.homeCard.w, CROPS.homeCard.h])};
  static const GardenLayerRect groundRect = ${rectConst(REGIONS.ground)};
  static const GardenLayerRect waterRect = ${rectConst(REGIONS.water)};

  static const Map<String, GardenLayerPlacement> elementPlacements = {
${placements}
  };

  static const List<List<double>> streamCenterline = [${centerline}];
  static const GardenLayerRect fireflyRegion = ${rectConst(MOTION.fireflyRegion)};
  static const List<List<double>> beeAnchors = [${bees}];
  static const List<double> fishAnchor = [${MOTION.fishAnchor[0]}, ${MOTION.fishAnchor[1]}];
  static const List<double> beehiveAnchor = [${MOTION.beehiveAnchor[0]}, ${MOTION.beehiveAnchor[1]}];
  static const double birdBandTop = ${MOTION.birdBand[0]};
  static const double birdBandBottom = ${MOTION.birdBand[1]};

  /// WebP layers that exist under assets/images/garden_art/. The asset
  /// resolver walks variants/stages downward through this set and falls back
  /// to the placeholder painter when nothing is available.
  static const Set<String> availableGardenArtFiles = <String>{
${files}
  };
}
`;
  mkdirSync(dirname(DART_OUT), { recursive: true });
  writeFileSync(DART_OUT, dart);
  console.log('wrote', DART_OUT);
}

emitDart();
console.log('layout emitted. Art waves (P4+) add SVG painters + AVAILABLE_FILES here.');
