import 'growth_models.dart';

const List<GrowthHabit> seededGrowthHabits = [
  GrowthHabit(
    id: 'h_pray_five',
    title: 'Pray the Five Daily Prayers',
    subtitle: 'Anchor your day with salah.',
    description: 'Guard each prayer in its time with calm presence.',
    category: GrowthHabitCategory.dailyWorship,
    pathIds: ['core-muslim-habits', 'foundations-of-light'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 1,
    lightReward: 20,
    streakEligible: true,
    reminderEnabled: true,
    reflectionPrompt: 'Which prayer felt most present today?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 1,
    isCustom: false,
    stage: 1,
  ),
  GrowthHabit(
    id: 'h_read_quran',
    title: 'Read Qur’an',
    subtitle: 'A daily portion, even small.',
    description: 'Read with attention and intention, even if only a few ayat.',
    category: GrowthHabitCategory.knowledge,
    pathIds: ['core-muslim-habits', 'foundations-of-light', 'quran-companion'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 1,
    lightReward: 16,
    streakEligible: true,
    reminderEnabled: true,
    reminderMode: GrowthReminderMode.timeWindow,
    reminderWindowType: GrowthReminderWindowType.evening,
    reflectionPrompt: 'What verse stayed with your heart today?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 2,
    isCustom: false,
    stage: 1,
    allowPartial: true,
  ),
  GrowthHabit(
    id: 'h_morning_adhkar',
    title: 'Morning Adhkar',
    subtitle: 'Begin with remembrance.',
    description: 'Keep a simple morning remembrance rhythm.',
    category: GrowthHabitCategory.sunnahPractices,
    pathIds: ['core-muslim-habits', 'foundations-of-light', 'sunnah-revival'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 1,
    lightReward: 12,
    streakEligible: true,
    reminderEnabled: true,
    reminderMode: GrowthReminderMode.prayerLinked,
    reminderPrayerAnchor: GrowthReminderPrayerAnchor.fajr,
    reminderOffsetMinutes: 15,
    reflectionPrompt: null,
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 3,
    isCustom: false,
    stage: 1,
  ),
  GrowthHabit(
    id: 'h_evening_adhkar',
    title: 'Evening Adhkar',
    subtitle: 'Close the day in remembrance.',
    description: 'Protect your evening with dhikr before rest.',
    category: GrowthHabitCategory.sunnahPractices,
    pathIds: ['core-muslim-habits', 'foundations-of-light', 'sunnah-revival'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 1,
    lightReward: 12,
    streakEligible: true,
    reminderEnabled: true,
    reminderMode: GrowthReminderMode.prayerLinked,
    reminderPrayerAnchor: GrowthReminderPrayerAnchor.maghrib,
    reminderOffsetMinutes: 20,
    reflectionPrompt: null,
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 4,
    isCustom: false,
    stage: 1,
  ),
  GrowthHabit(
    id: 'h_make_dua',
    title: 'Make Du’a',
    subtitle: 'Ask Allah with sincerity.',
    description: 'Keep one sincere personal du’a daily.',
    category: GrowthHabitCategory.dailyWorship,
    pathIds: ['core-muslim-habits', 'foundations-of-light'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 1,
    lightReward: 10,
    streakEligible: true,
    reminderEnabled: true,
    reflectionPrompt: 'What did you place before Allah today?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 5,
    isCustom: false,
    stage: 1,
  ),
  GrowthHabit(
    id: 'h_gratitude',
    title: 'Practice Gratitude',
    subtitle: 'Name one blessing daily.',
    description: 'Write or say one gratitude with attention.',
    category: GrowthHabitCategory.reflectionGratitude,
    pathIds: ['core-muslim-habits', 'foundations-of-light', 'strengthening-heart'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 1,
    lightReward: 10,
    streakEligible: true,
    reminderEnabled: true,
    reminderMode: GrowthReminderMode.timeWindow,
    reminderWindowType: GrowthReminderWindowType.beforeSleep,
    reflectionPrompt: 'What blessing softened your heart today?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 6,
    isCustom: false,
    stage: 1,
  ),
  GrowthHabit(
    id: 'h_harmful_speech',
    title: 'Avoid Harmful Speech',
    subtitle: 'Guard the tongue.',
    description: 'Pause before words that may hurt or backbite.',
    category: GrowthHabitCategory.character,
    pathIds: ['core-muslim-habits', 'foundations-of-light', 'character-builder'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 1,
    lightReward: 12,
    streakEligible: true,
    reminderEnabled: true,
    reflectionPrompt: null,
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 7,
    isCustom: false,
    stage: 1,
  ),
  GrowthHabit(
    id: 'h_sunnah_prayer',
    title: 'Pray One Sunnah Prayer',
    subtitle: 'Add one voluntary salah.',
    description: 'Maintain one Sunnah prayer with consistency.',
    category: GrowthHabitCategory.sunnahPractices,
    pathIds: ['core-muslim-habits', 'strengthening-heart', 'sunnah-revival'],
    recurrenceType: GrowthHabitRecurrenceType.weekdaysOnly,
    weekdays: [1, 2, 3, 4, 5],
    frequencyTarget: 5,
    difficulty: 2,
    lightReward: 14,
    streakEligible: true,
    reminderEnabled: false,
    reflectionPrompt: null,
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 8,
    isCustom: false,
    stage: 2,
  ),
  GrowthHabit(
    id: 'h_salawat',
    title: 'Send Salawat',
    subtitle: 'Daily connection with the Prophet ﷺ.',
    description: 'Send salawat with love and steady rhythm.',
    category: GrowthHabitCategory.sunnahPractices,
    pathIds: ['core-muslim-habits', 'strengthening-heart', 'sunnah-revival'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 2,
    lightReward: 10,
    streakEligible: true,
    reminderEnabled: false,
    reflectionPrompt: null,
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 9,
    isCustom: false,
    stage: 2,
  ),
  GrowthHabit(
    id: 'h_istighfar',
    title: 'Istighfar',
    subtitle: 'Return often with repentance.',
    description: 'Keep a simple daily istighfar target.',
    category: GrowthHabitCategory.reflectionGratitude,
    pathIds: ['core-muslim-habits', 'strengthening-heart'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 2,
    lightReward: 10,
    streakEligible: true,
    reminderEnabled: false,
    reflectionPrompt: 'What do you seek forgiveness for today?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 10,
    isCustom: false,
    stage: 2,
  ),
  GrowthHabit(
    id: 'h_study_knowledge',
    title: 'Study Islamic Knowledge',
    subtitle: 'Learn with structure.',
    description: 'Read or listen to beneficial knowledge intentionally.',
    category: GrowthHabitCategory.knowledge,
    pathIds: ['core-muslim-habits', 'strengthening-heart', 'path-of-excellence'],
    recurrenceType: GrowthHabitRecurrenceType.weeklyTarget,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 4,
    difficulty: 2,
    lightReward: 14,
    streakEligible: true,
    reminderEnabled: true,
    reflectionPrompt: 'What one lesson can you apply today?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 11,
    isCustom: false,
    stage: 2,
    allowPartial: true,
  ),
  GrowthHabit(
    id: 'h_help_someone',
    title: 'Help Someone',
    subtitle: 'Serve quietly.',
    description: 'Offer one practical help to someone around you.',
    category: GrowthHabitCategory.charityService,
    pathIds: ['core-muslim-habits', 'strengthening-heart', 'family-service'],
    recurrenceType: GrowthHabitRecurrenceType.weeklyTarget,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 3,
    difficulty: 2,
    lightReward: 14,
    streakEligible: true,
    reminderEnabled: false,
    reflectionPrompt: null,
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 12,
    isCustom: false,
    stage: 2,
  ),
  GrowthHabit(
    id: 'h_give_charity',
    title: 'Give Charity',
    subtitle: 'A small regular sadaqah.',
    description: 'Set a realistic rhythm of giving.',
    category: GrowthHabitCategory.charityService,
    pathIds: ['core-muslim-habits', 'strengthening-heart', 'family-service'],
    recurrenceType: GrowthHabitRecurrenceType.weeklyTarget,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 2,
    difficulty: 2,
    lightReward: 18,
    streakEligible: true,
    reminderEnabled: true,
    reflectionPrompt: 'How did giving soften your heart?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 13,
    isCustom: false,
    stage: 2,
  ),
  GrowthHabit(
    id: 'h_patience_anger',
    title: 'Practice Patience / Control Anger',
    subtitle: 'Respond with restraint.',
    description: 'Choose sabr at one trigger point each day.',
    category: GrowthHabitCategory.character,
    pathIds: ['core-muslim-habits', 'strengthening-heart', 'character-builder'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 2,
    lightReward: 15,
    streakEligible: true,
    reminderEnabled: false,
    reflectionPrompt: 'Where did patience protect you today?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 14,
    isCustom: false,
    stage: 2,
  ),
  GrowthHabit(
    id: 'h_tahajjud',
    title: 'Tahajjud Occasionally',
    subtitle: 'Night worship with mercy.',
    description: 'Aim for occasional night prayer without pressure.',
    category: GrowthHabitCategory.sunnahPractices,
    pathIds: ['core-muslim-habits', 'path-of-excellence', 'sunnah-revival'],
    recurrenceType: GrowthHabitRecurrenceType.weeklyTarget,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 1,
    difficulty: 3,
    lightReward: 26,
    streakEligible: true,
    reminderEnabled: false,
    reflectionPrompt: null,
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 15,
    isCustom: false,
    stage: 3,
  ),
  GrowthHabit(
    id: 'h_sunnah_fasts',
    title: 'Fast Sunnah Fasts',
    subtitle: 'A disciplined rhythm.',
    description: 'Track optional fasting days sustainably.',
    category: GrowthHabitCategory.healthDiscipline,
    pathIds: ['core-muslim-habits', 'path-of-excellence', 'sunnah-revival'],
    recurrenceType: GrowthHabitRecurrenceType.weeklyTarget,
    weekdays: [1, 4],
    frequencyTarget: 1,
    difficulty: 3,
    lightReward: 24,
    streakEligible: true,
    reminderEnabled: false,
    reflectionPrompt: null,
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 16,
    isCustom: false,
    stage: 3,
  ),
  GrowthHabit(
    id: 'h_memorize_quran',
    title: 'Memorize Qur’an',
    subtitle: 'One ayah at a time.',
    description: 'Build long-term memorization patiently.',
    category: GrowthHabitCategory.knowledge,
    pathIds: ['core-muslim-habits', 'path-of-excellence', 'quran-companion'],
    recurrenceType: GrowthHabitRecurrenceType.weeklyTarget,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 4,
    difficulty: 3,
    lightReward: 20,
    streakEligible: true,
    reminderEnabled: true,
    reflectionPrompt: null,
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 17,
    isCustom: false,
    stage: 3,
    allowPartial: true,
  ),
  GrowthHabit(
    id: 'h_reflect_verse',
    title: 'Reflect on One Verse',
    subtitle: 'From reading to living.',
    description: 'Pause to apply one ayah practically.',
    category: GrowthHabitCategory.reflectionGratitude,
    pathIds: ['core-muslim-habits', 'path-of-excellence', 'quran-companion'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 3,
    lightReward: 16,
    streakEligible: true,
    reminderEnabled: true,
    reflectionPrompt: 'Which verse guided your decisions today?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 18,
    isCustom: false,
    stage: 3,
    allowPartial: true,
  ),
  GrowthHabit(
    id: 'h_reconnect_family',
    title: 'Reconnect with Family',
    subtitle: 'Keep ties alive.',
    description: 'Reach out or support family with ihsan.',
    category: GrowthHabitCategory.charityService,
    pathIds: ['core-muslim-habits', 'path-of-excellence', 'family-service'],
    recurrenceType: GrowthHabitRecurrenceType.weeklyTarget,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 3,
    difficulty: 3,
    lightReward: 18,
    streakEligible: true,
    reminderEnabled: true,
    reflectionPrompt: 'Which tie did you strengthen this week?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 19,
    isCustom: false,
    stage: 3,
    allowPartial: true,
  ),
  GrowthHabit(
    id: 'h_humility',
    title: 'Practice Humility',
    subtitle: 'Lower the ego, raise sincerity.',
    description: 'Choose humble responses and intentions.',
    category: GrowthHabitCategory.character,
    pathIds: ['core-muslim-habits', 'path-of-excellence', 'character-builder'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 3,
    lightReward: 16,
    streakEligible: true,
    reminderEnabled: false,
    reflectionPrompt: null,
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 20,
    isCustom: false,
    stage: 3,
  ),
  GrowthHabit(
    id: 'h_day_end_reflection',
    title: 'End Day with Reflection and Tawbah',
    subtitle: 'Close with review and return.',
    description: 'A brief muhasabah before sleep.',
    category: GrowthHabitCategory.reflectionGratitude,
    pathIds: ['core-muslim-habits', 'path-of-excellence', 'strengthening-heart'],
    recurrenceType: GrowthHabitRecurrenceType.daily,
    weekdays: [1, 2, 3, 4, 5, 6, 7],
    frequencyTarget: 7,
    difficulty: 3,
    lightReward: 18,
    streakEligible: true,
    reminderEnabled: true,
    reminderMode: GrowthReminderMode.timeWindow,
    reminderWindowType: GrowthReminderWindowType.beforeSleep,
    reflectionPrompt: 'What do you seek to improve tomorrow?',
    active: true,
    muted: false,
    hidden: false,
    entrustable: true,
    entrustToAllah: false,
    sortOrder: 21,
    isCustom: false,
    stage: 3,
  ),
];

const List<GrowthPath> seededGrowthPaths = [
  GrowthPath(
    id: 'core-muslim-habits',
    title: '21 Core Muslim Habits',
    subtitle: 'Structured habit foundations in 3 stages.',
    description:
        'A complete core system that moves from foundations to excellence through steady, sincere practice.',
    difficulty: GrowthPathDifficulty.steady,
    totalHabits: 21,
    estimatedCommitment: '15-30 min/day',
    icon: 'spark',
    habitIds: [
      'h_pray_five',
      'h_read_quran',
      'h_morning_adhkar',
      'h_evening_adhkar',
      'h_make_dua',
      'h_gratitude',
      'h_harmful_speech',
      'h_sunnah_prayer',
      'h_salawat',
      'h_istighfar',
      'h_study_knowledge',
      'h_help_someone',
      'h_give_charity',
      'h_patience_anger',
      'h_tahajjud',
      'h_sunnah_fasts',
      'h_memorize_quran',
      'h_reflect_verse',
      'h_reconnect_family',
      'h_humility',
      'h_day_end_reflection',
    ],
    unlockPathId: null,
    unlockLight: 0,
    stage: 1,
  ),
  GrowthPath(
    id: 'foundations-of-light',
    title: 'Foundations of Light',
    subtitle: 'Build your base rhythm.',
    description:
        'The first layer of consistency: prayer, Qur’an, adhkar, du’a, gratitude, and speech discipline.',
    difficulty: GrowthPathDifficulty.beginner,
    totalHabits: 7,
    estimatedCommitment: '10-18 min/day',
    icon: 'sun',
    habitIds: [
      'h_pray_five',
      'h_read_quran',
      'h_morning_adhkar',
      'h_evening_adhkar',
      'h_make_dua',
      'h_gratitude',
      'h_harmful_speech',
    ],
    unlockPathId: null,
    unlockLight: 0,
    stage: 1,
  ),
  GrowthPath(
    id: 'strengthening-heart',
    title: 'Strengthening the Heart',
    subtitle: 'Inner consistency and softness.',
    description:
        'Increase salawat, istighfar, service, and patient self-control while deepening gratitude and reflection.',
    difficulty: GrowthPathDifficulty.steady,
    totalHabits: 9,
    estimatedCommitment: '12-24 min/day',
    icon: 'heart',
    habitIds: [
      'h_gratitude',
      'h_sunnah_prayer',
      'h_salawat',
      'h_istighfar',
      'h_study_knowledge',
      'h_help_someone',
      'h_give_charity',
      'h_patience_anger',
      'h_day_end_reflection',
    ],
    unlockPathId: 'foundations-of-light',
    unlockLight: 250,
    stage: 2,
  ),
  GrowthPath(
    id: 'path-of-excellence',
    title: 'Path of Excellence',
    subtitle: 'Move from consistency to ihsan.',
    description:
        'A deeper journey with tahajjud, sunnah fasting, memorization, humility, and end-of-day review.',
    difficulty: GrowthPathDifficulty.deep,
    totalHabits: 10,
    estimatedCommitment: '20-40 min/day',
    icon: 'mountain',
    habitIds: [
      'h_study_knowledge',
      'h_tahajjud',
      'h_sunnah_fasts',
      'h_memorize_quran',
      'h_reflect_verse',
      'h_reconnect_family',
      'h_humility',
      'h_day_end_reflection',
      'h_patience_anger',
      'h_give_charity',
    ],
    unlockPathId: 'strengthening-heart',
    unlockLight: 520,
    stage: 3,
  ),
  GrowthPath(
    id: 'quran-companion',
    title: 'Qur’an Companion',
    subtitle: 'Read, reflect, memorize, apply.',
    description:
        'A Qur’an-centered growth path for daily companionship with recitation and reflection.',
    difficulty: GrowthPathDifficulty.steady,
    totalHabits: 4,
    estimatedCommitment: '12-20 min/day',
    icon: 'book',
    habitIds: [
      'h_read_quran',
      'h_memorize_quran',
      'h_reflect_verse',
      'h_study_knowledge',
    ],
    unlockPathId: null,
    unlockLight: 0,
    stage: 2,
  ),
  GrowthPath(
    id: 'character-builder',
    title: 'Character Builder',
    subtitle: 'Akhlaq in daily life.',
    description:
        'Focus on speech, patience, humility, and practical everyday conduct.',
    difficulty: GrowthPathDifficulty.steady,
    totalHabits: 4,
    estimatedCommitment: '8-15 min/day',
    icon: 'leaf',
    habitIds: [
      'h_harmful_speech',
      'h_patience_anger',
      'h_humility',
      'h_help_someone',
    ],
    unlockPathId: null,
    unlockLight: 0,
    stage: 2,
  ),
  GrowthPath(
    id: 'sunnah-revival',
    title: 'Sunnah Revival',
    subtitle: 'Small Sunnah acts restored.',
    description:
        'Revive prophetic daily practices with sustainable weekly commitment.',
    difficulty: GrowthPathDifficulty.steady,
    totalHabits: 6,
    estimatedCommitment: '10-20 min/day',
    icon: 'crescent',
    habitIds: [
      'h_morning_adhkar',
      'h_evening_adhkar',
      'h_sunnah_prayer',
      'h_salawat',
      'h_tahajjud',
      'h_sunnah_fasts',
    ],
    unlockPathId: null,
    unlockLight: 0,
    stage: 2,
  ),
  GrowthPath(
    id: 'family-service',
    title: 'Family & Service',
    subtitle: 'Mercy through relationships and giving.',
    description:
        'A path for strengthening ties, regular service, and consistent charity.',
    difficulty: GrowthPathDifficulty.steady,
    totalHabits: 4,
    estimatedCommitment: '8-16 min/day',
    icon: 'family',
    habitIds: [
      'h_help_someone',
      'h_give_charity',
      'h_reconnect_family',
      'h_gratitude',
    ],
    unlockPathId: null,
    unlockLight: 0,
    stage: 2,
  ),
];
